services:
  nextjs-app: 
    build: 
      context: .
    environment:
      - MONGODB_URI=${MONGODB_URI}  
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    ports:
      - "3000:3000"

