name: Feature Request
description: Suggest a new feature for the Seminar Hall Booking Website
body:
  - type: markdown
    attributes:
      value: |
        <div align="center">
          <h2>Seminar Hall Booking Software — Feature Request</h2>
          <p><em>Thanks for taking the time to help us improve the platform!</em></p>
        </div>

        > [!IMPORTANT]
        > - Provide clear, descriptive titles.
        > - Search existing issues to avoid duplicates.
        > - Use this form for feature requests only.
        > - Include reproduction steps and visuals if possible.
        > - Be as specific as you can!

  - type: checkboxes
    id: prechecks
    attributes:
      label: Preliminary Checks
      description: Please confirm the following before submitting.
      options:
        - label: I have read the instructions above.
          required: true
        - label: I have searched the existing issues to ensure this is not a duplicate.
          required: true
        - label: This is a **feature request**, not a bug report.
          required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos
      description: If applicable, please attach visuals to illustrate the new feature.

  - type: input
    id: version
    attributes:
      label: DK24 Website Version
      description: Provide the version if visible (e.g., `1.0.0-beta`). Leave blank if unknown.
      placeholder: e.g. 1.0.0-beta
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component/Feature Affected
      options:
        - Other
        - Homepage
        - Projects Section
        - Join Platform
        - Community Directory
        - TEAM Model
        - Event Registration
        - User Onboarding
        - Dashboard
        - Responsive Layout
        - Authentication
        - Forms
        - Dark Mode
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Console or Network Logs (if any)
      description: Paste any error messages or logs from your browser's developer tools.
      render: shell

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Willing to Contribute?
      description: Are you willing to implement this feature?
      options:
        - Yes, I can implement it.
        - No, I just want to report it.
    validations:
      required: true
